version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 #debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/webapp_dev?schema=public
      PORT: 8000

volumes:
  postgres-data:
